# Generated by Django 2.0.6 on 2018-06-20 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.IntegerField(default=0)),
                ('account_child', models.IntegerField(default=0)),
                ('potential', models.CharField(max_length=200)),
                ('pipeline', models.CharField(max_length=200)),
                ('stage', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Account_Risk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.IntegerField(default=0)),
                ('account_name', models.CharField(max_length=200)),
                ('customer_name', models.CharField(max_length=200)),
                ('account_risk', models.CharField(max_length=3000)),
            ],
        ),
    ]
